name: very_good_app

on:
  push:
    tags:
      - v1.*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.0

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: flutter format --set-exit-if-changed lib test

      - name: Analyze
        run: flutter analyze lib test

      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1

      - name: setup keystore
        env:
          SIGNING_KEY: ${{ secrets.ANDROID_KEYSTORE }}
        run: |
          echo $SIGNING_KEY | base64 -di > android/app/key.jks
          pwd
          ls android/app

      - name: build release
        env:
          ANDROID_KEYSTORE_ALIAS: upload
          ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD: 123456
          ANDROID_KEYSTORE_PASSWORD: 123456
          ANDROID_KEYSTORE_PATH: key.jks
        run: |
          flutter build apk --release --flavor production --target lib/main_production.dart

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          token: ${{ secrets.TOKEN }}

